-- Below content inherited from Test, which is file runner initially generated by BNFC. 

module Main ( main ) where

import Prelude                     ( ($), unlines, IO, (>>=), mapM_, putStrLn, getContents )
import System.Environment          ( getArgs )

import Interpreter.Interpreter     ( run, runFile )

usage :: IO ()
usage = do
  putStrLn $ unlines
    [ "usage: Call with one of the following argument combinations:"
    , "  --help          Display this help message."
    , "  (no arguments)  Parse stdin verbosely."
    , "  (file)          Parse content of file verbosely."
    ]

main :: IO ()
main = do
  args <- getArgs
  case args of
    ["--help"] -> usage
    []         -> getContents >>= run
    fs         -> mapM_ runFile fs
